"""Every result number in main.tex, computed from the result files.

Writes ``paper/numbers.tex`` (``\\defval{key}{value}`` lines, read by ``\\val{key}`` in
main.tex) and the result tables under ``paper/tables/``. main.tex types no result by hand: change a
result file, rerun this, rebuild, and the PDF follows. A key the tex asks for that this script did
not write prints as a red ``??key`` and a LaTeX warning, which ``camera.sh`` turns into a failure,
as it does the warning written when a run is still partial.

Sources (results/clt_scale/):
  readout_sampled_answers.json      E4, the replication with sampled answers (main text)
  readout_generation_check.json     E2, the first generation check (rules appendix, reproduction)
  occlusion_readout_audit.json      the evidence blocks of the first 20 films (location, effusion)
  donor_sets_patient_disjoint.json  E3, patient-disjoint donor sets (selection section)
  clamp_contrastive_answers.json    E5, contrastive and anchored feature sets (selection section)
  readout_eval_answers_<model>.json E6, the stratified evaluation, one file per model (appendix)
  readout_eval_matched.json         E7, the corrected test (scope); runs: ..._matched_<model>.json
  clamp_live_mlp.json               E8, the suppression added to the live MLPs
  clamp_live_dose.json              E9, weaker live suppression at a matched answer change
  answer_text_checks.json           post-hoc checks of E4's answers: other parse rules, text
                                    degeneration, ceiling (scripts/answer_text_checks.py)
  logs/<run>.log                    the generation runs' logs (compute times)

Run from the repo root: .venv/bin/python paper/make_numbers.py
"""
from __future__ import annotations

import json
import re
import sys
from collections import Counter
from pathlib import Path

import numpy as np
from scipy.stats import binom

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "scripts"))
import clamp_contrastive_answers as e5mod  # noqa: E402
import readout_eval_answers as e6mod  # noqa: E402
from readout_sampled_answers import CLAMP_OPS, analyze  # noqa: E402
from tracecxr.intervention.generation_check import call  # noqa: E402

R = ROOT / "results/clt_scale"
OUT = ROOT / "paper"
NB = 8  # occlusion blocks per side

# arm key in the result files -> short key in the tex, and its row label in the tables
ARMS = {"base": ("base", "None"),
        "clamp_scale-1": ("scale1", "Suppress, \\texttt{scale} $-1$"),
        "clamp_ablate+0": ("ablate", "Suppress, \\texttt{ablate}"),
        "clamp_scale-2": ("scale2", "Suppress, \\texttt{scale} $-2$"),
        "black": ("black", "Evidence block, black"),
        "mean": ("mean", "Evidence block, mean fill"),
        "blur": ("blur", "Evidence block, blur"),
        "border": ("border", "Border block, black")}
OCC_ARMS = ("black", "mean", "blur", "border")
TP = {"tp_cardiomegaly": "cardiomegaly", "tp_effusion": "effusion",
      "tp_pneumothorax": "pneumothorax"}

vals: dict[str, str] = {}
warnings: list[str] = []


# --------------------------------------------------------------------------------------------
# formatting
# --------------------------------------------------------------------------------------------
def num(x: float, d: int = 2, sign: bool = False) -> str:
    s = f"{x:+.{d}f}" if sign else f"{x:.{d}f}"
    return "\\ensuremath{" + s + "}"


def ci(t: tuple | list, d: int = 2, sign: bool = False) -> str:
    m, lo, hi = t
    f = (lambda v: f"{v:+.{d}f}") if sign else (lambda v: f"{v:.{d}f}")
    return f"\\ensuremath{{{f(m)}\\;[{f(lo)},\\,{f(hi)}]}}"


def verdict(v: str) -> str:
    return "\\textsc{" + v.lower() + "}"


def tex_escape(s: str) -> str:
    rep = {"\\": "\\textbackslash{}", "{": "\\{", "}": "\\}", "#": "\\#", "$": "\\$", "%": "\\%",
           "&": "\\&", "_": "\\_", "^": "\\^{}", "~": "\\~{}"}
    return "".join(rep.get(c, c) for c in s)


def put(key: str, value: object) -> None:
    if key in vals:
        raise KeyError(f"{key} written twice")
    vals[key] = str(value)


def table(name: str, text: str) -> None:
    (OUT / "tables").mkdir(exist_ok=True)
    (OUT / "tables" / f"{name}.tex").write_text(
        f"% generated by paper/make_numbers.py; do not edit\n{text}\n")


# --------------------------------------------------------------------------------------------
# E4: sampled answers
# --------------------------------------------------------------------------------------------
def routes(recs: list[dict]) -> dict[str, float]:
    """Pooled over films and samples: share answering directly / reasoning first, and outcomes."""
    direct = [(w, p) for a in recs for w, p in zip(a["samples_open"], a["samples_parsed"],
                                                    strict=True) if w in ("yes", "no")]
    reasoned = [p for a in recs for w, p in zip(a["samples_open"], a["samples_parsed"],
                                                 strict=True) if w not in ("yes", "no")]
    n = len(direct) + len(reasoned)
    c = Counter(reasoned)
    nr = max(len(reasoned), 1)
    return {"direct": len(direct) / n, "direct_yes": np.mean([p == "YES" for _, p in direct]),
            "reasoned": len(reasoned) / n, "r_yes": c["YES"] / nr, "r_no": c["NO"] / nr,
            "r_none": c["NONE"] / nr}


def missed(recs: list[dict]) -> list[dict]:
    """Films whose greedy answer is no while P_norm still calls yes."""
    return [x for x in recs if x["greedy_parsed"] == "NO" and call(x["norm"]) == "YES"]


def e4() -> None:  # noqa: PLR0915
    d = json.loads((R / "readout_sampled_answers.json").read_text())
    rows = d["rows"]
    n_draw = sum(len(v) for v in d["draw"].values())
    if "summary" in d and len(rows) == n_draw:
        res = {"summary": d["summary"], "verdicts": d["verdicts"]}
    else:
        warnings.append(f"E4 is partial ({len(rows)} of {n_draw} films)")
        res = analyze(rows, n_boot=2000)
    S, V = res["summary"], res["verdicts"]
    fp_rows = [r for r in rows if r["group"].startswith("fp_")]
    fp = S["fp"]

    put("e4.nsamples", d.get("n_samples", 50))
    put("e4.maxtok", d.get("max_new_tokens", 128))
    put("n.fp", fp["base"]["n"])
    put("n.fppatients", len({e6mod.patient(r["image"]) for r in fp_rows}))
    for g in ("fp_banked", "fp_fresh", *TP):
        put(f"n.{g.replace('_', '')}", len(d["draw"].get(g, [])))
    put("n.tp", sum(len(d["draw"].get(g, [])) for g in TP))
    scanned = Counter(k.split("/")[0] for k in d.get("greedy_draw", {}))
    for g in ("fp_fresh", *TP):
        put(f"scanned.{g.replace('_', '')}", scanned.get(g, 0))
    put("firsttok.maxdiff", num(max(a["first_token_diff"] for r in rows
                                    for a in r["arms"].values()), 3))
    gaps0 = [r["arms"]["base"]["gap"] for r in fp_rows]
    put("fp.base.gapmedian", num(float(np.median(gaps0)), 1))
    # odds of "yes" over "no" at the median margin, two significant figures
    odds = float(np.exp(np.median(gaps0)))
    put("fp.base.gapodds", f"{float(f'{odds:.2g}'):,.0f}".replace(",", "{,}"))

    for arm, (k, _) in ARMS.items():
        a = fp[arm]
        recs = [r["arms"][arm] for r in fp_rows]
        put(f"fp.{k}.raw", num(a["raw"], 3))
        put(f"fp.{k}.raw2", num(a["raw"], 2))
        put(f"fp.{k}.norm", num(a["norm"], 3))
        put(f"fp.{k}.mass", num(a["mass"], 2))
        put(f"fp.{k}.pno", num(a["mass"] - a["raw"], 3))
        put(f"fp.{k}.s", num(a["s_mean"][0], 2))
        put(f"fp.{k}.sci", ci(a["s_mean"]))
        put(f"fp.{k}.c", num(a["c_mean"][0], 2))
        put(f"fp.{k}.greedyno", a["greedy"].get("NO", 0))
        put(f"fp.{k}.greedynone", a["greedy"].get("NONE", 0))
        put(f"fp.{k}.flipsraw", a["flips_raw"])
        put(f"fp.{k}.flipsnorm", a["flips_norm"])
        put(f"fp.{k}.gnonormyes", len(missed(recs)))
        put(f"fp.{k}.none", num(a["sampled"].get("NONE", 0.0), 2))
        put(f"fp.{k}.gapmin", num(min(r["gap"] for r in recs), 1))
        put(f"fp.{k}.based", num(a["first_token"].get("Based", 0.0), 2))
        put(f"fp.{k}.pyesbased", num(a["opening"].get("based", {}).get("p_yes", float("nan")),
                                     2))
        put(f"fp.{k}.terse", sum(r["greedy"].strip() == "Yes." for r in recs))
        if arm == "base":
            continue
        put(f"fp.{k}.dgap", num(a["gap_change_median"], 1, sign=True))
        put(f"fp.{k}.sdrop", num(a["s_drop"][0], 2))
        put(f"fp.{k}.sdropci", ci(a["s_drop"]))
        put(f"fp.{k}.cdropci", ci(a["c_drop"]))
        for rd in ("raw", "norm"):
            put(f"fp.{k}.{rd}drop", num(a[f"{rd}_drop"][0], 2))
            for tag in ("s", "c"):
                vs = a[f"{rd}_vs_{tag}"]
                sfx = "" if tag == "s" else "c"
                put(f"fp.{k}.{rd}vs{sfx}", ci(vs["diff"], sign=True))
                put(f"fp.{k}.{rd}vs{sfx}.v", verdict(vs["verdict"]))
        if arm in CLAMP_OPS:
            put(f"fp.{k}.e2rule", verdict(a["e2_rule"]))
    for g in ("fp_banked", "fp_fresh"):
        if g in S:
            gk = g.replace("_", "")
            for arm in CLAMP_OPS:
                k = ARMS[arm][0]
                put(f"{gk}.{k}.sdropci", ci(S[g][arm]["s_drop"]))
                put(f"{gk}.{k}.greedyno", S[g][arm]["greedy"].get("NO", 0))
                put(f"{gk}.{k}.e2rule", verdict(S[g][arm]["e2_rule"]))
            put(f"{gk}.base.s", num(S[g]["base"]["s_mean"][0], 2))
    clamp_pno = max(fp[a]["mass"] - fp[a]["raw"] for a in CLAMP_OPS)
    put("fp.clamp.pnomax", num(clamp_pno, 3))
    put("fp.clamp.gapmin", num(min(r["arms"][a]["gap"] for r in fp_rows for a in CLAMP_OPS), 1))
    put("fp.clamp.terse", sum(r["arms"][a]["greedy"].strip() == "Yes." for r in fp_rows
                              for a in CLAMP_OPS))
    put("fp.clamp.nfilmarms", len(fp_rows) * len(CLAMP_OPS))
    for arm in CLAMP_OPS:
        put(f"fp.{ARMS[arm][0]}.dgapabs", num(abs(fp[arm]["gap_change_median"]), 1))
    # occlusion as the reference: how far either readout strays from s, against P_norm's shortfall
    put("occ.maxdiff", num(max(abs(fp[a][f"{rd}_vs_s"]["diff"][0]) for a in OCC_ARMS
                               for rd in ("raw", "norm")), 2))
    put("fp.clamp.minshortfall", num(min(-fp[a]["norm_vs_s"]["diff"][0] for a in CLAMP_OPS), 2))
    occ_mis = {(a, rd) for a in OCC_ARMS for rd in ("raw", "norm")
               if fp[a][f"{rd}_vs_s"]["verdict"] == "MISREADS"}
    if occ_mis != {("black", "norm"), ("blur", "raw")} or any(
            fp[a][f"{rd}_vs_s"]["diff"][0] <= 0 for a, rd in occ_mis):
        warnings.append(f"occlusion MISREADS cells are {sorted(occ_mis)}; prose names black "
                        "P_norm and blur P_raw, both overshooting")
    # film by film (post hoc): of the films whose greedy answer is no, how many P_norm still calls yes
    for name, arms in (("clamp", CLAMP_OPS), ("occ", ("black", "mean", "blur"))):
        recs = [r["arms"][a] for r in fp_rows for a in arms]
        put(f"pf.{name}.gno", sum(x["greedy_parsed"] == "NO" for x in recs))
        put(f"pf.{name}.gnoyes", len(missed(recs)))
        # the counts are over (film, variant) pairs; also count the distinct films behind them
        put(f"pf.{name}.gnofilms", sum(any(r["arms"][a]["greedy_parsed"] == "NO" for a in arms)
                                       for r in fp_rows))
        put(f"pf.{name}.gnoyesfilms", sum(bool(missed([r["arms"][a] for a in arms]))
                                          for r in fp_rows))
    put("pf.clamp.missmin", num(min(x["norm"] for r in fp_rows for a in CLAMP_OPS
                                    for x in missed([r["arms"][a]])), 2))
    # last-layer features: edited at image positions, their output reaches no later token
    last = clt_layers() - 1
    n_last = [sum(lay == last for lay, _ in r["clamp_pairs"]) for r in fp_rows]
    put("clamp.nlast.mean", num(np.mean(n_last), 0))
    put("clamp.nlast.min", min(n_last))
    put("clamp.nlast.max", max(n_last))
    put("fp.scale1.rawvsthree", ci(fp["clamp_scale-1"]["raw_vs_s"]["diff"], 3, sign=True))
    put("fp.clamp.maxshortfall", num(max(-fp[a]["norm_vs_s"]["diff"][0] for a in CLAMP_OPS), 2))

    # verdicts
    for key in ("V1_raw_s", "V1_norm_s", "V1_raw_c", "V1_norm_c", "V3_s", "V3_c", "V2"):
        if key in V:
            put(f"v.{key.replace('_', '')}", verdict(V[key]))

    # routes table and numbers
    rt = {arm: routes([r["arms"][arm] for r in fp_rows]) for arm in ARMS}
    for arm, (k, _) in ARMS.items():
        for f in ("direct", "direct_yes", "reasoned", "r_yes", "r_no", "r_none"):
            put(f"route.{k}.{f.replace('_', '')}", num(rt[arm][f], 2))
        # share of all samples that reason first and conclude yes: what P_raw leaves out
        put(f"route.{k}.ryesall", num(rt[arm]["reasoned"] * rt[arm]["r_yes"], 2))
    lines = []
    for arm in ("base", *CLAMP_OPS, "black"):
        t = rt[arm]
        lines.append(f"{ARMS[arm][1]} & {t['direct']:.2f} & {t['direct_yes']:.2f} & "
                     f"{t['reasoned']:.2f} & {t['r_yes']:.2f} / {t['r_no']:.2f} / "
                     f"{t['r_none']:.2f} \\\\")
    table("routes", "\\begin{tabular}{lcccc}\n\\toprule\n"
          "& \\multicolumn{2}{c}{answers directly} & \\multicolumn{2}{c}{reasons first} \\\\\n"
          "\\cmidrule(lr){2-3}\\cmidrule(lr){4-5}\n"
          "Intervention & share & says yes & share & says yes / no / neither \\\\\n\\midrule\n"
          + "\n".join(lines) + "\n\\bottomrule\n\\end{tabular}")

    # main table: readouts and answers
    lines = []
    for arm, (_k, label) in ARMS.items():
        a = fp[arm]
        dg = "--" if arm == "base" else f"${a['gap_change_median']:+.1f}$"
        fl = f"{a['flips_raw']} / {a['flips_norm']}"
        nm = len(missed([r["arms"][arm] for r in fp_rows]))
        lines.append(f"{label} & {a['raw']:.3f} & {a['norm']:.3f} & {dg} & {fl} & "
                     f"{a['s_mean'][0]:.2f} & {a['greedy'].get('NO', 0)} ({nm}) \\\\")
        if arm == "clamp_scale-2":
            lines.append("\\midrule")
    table("main", "\\begin{tabular}{lcccccc}\n\\toprule\n"
          "& \\multicolumn{4}{c}{first token} & \\multicolumn{2}{c}{written answer} \\\\\n"
          "\\cmidrule(lr){2-5}\\cmidrule(lr){6-7}\n"
          "Intervention & $\\Praw$ & $\\Pnorm$ & median $\\Delta$ change & below $0.5$ "
          "& $s$ & greedy no \\\\\n"
          "& & & (nats) & ($\\Praw$ / $\\Pnorm$) & & ($\\Pnorm$ yes) \\\\\n\\midrule\n"
          + "\n".join(lines) + "\n\\bottomrule\n\\end{tabular}")

    # the pre-registered comparison: readout drop minus answer drop
    def cell(t: tuple, sign: bool = True, d: int = 2) -> str:
        f = f"+.{d}f" if sign else f".{d}f"
        z = "0." + "0" * d
        return (f"${t[0]:{f}}$ {{\\scriptsize[${t[1]:{f}}$,\\,${t[2]:{f}}$]}}"
                .replace(f"$-{z}$", f"${z}$").replace(f"$+{z}$", f"${z}$"))

    short = {"clamp_scale-1": "\\texttt{scale} $-1$", "clamp_ablate+0": "\\texttt{ablate}",
             "clamp_scale-2": "\\texttt{scale} $-2$", "black": "evidence, black",
             "mean": "evidence, mean", "blur": "evidence, blur", "border": "border, black"}
    lines = ["\\multicolumn{6}{l}{\\emph{Suppression}} \\\\"]
    for arm in short:
        label = "\\quad " + short[arm]
        a = fp[arm]
        if arm == "black":
            lines.append("\\multicolumn{6}{l}{\\emph{Occlusion (reference)}} \\\\")
        lines.append(f"{label} & {cell(a['s_drop'], False)} & {cell(a['raw_vs_s']['diff'])} & "
                     f"{verdict(a['raw_vs_s']['verdict'])} & {cell(a['norm_vs_s']['diff'])} & "
                     f"{verdict(a['norm_vs_s']['verdict'])} \\\\")
    table("v1", "\\begin{tabular}{lccccc}\n\\toprule\n"
          "& & \\multicolumn{2}{c}{$\\Praw$} & \\multicolumn{2}{c}{$\\Pnorm$} \\\\\n"
          "\\cmidrule(lr){3-4}\\cmidrule(lr){5-6}\n"
          "Intervention & drop in $s$ & difference & verdict & difference & verdict "
          "\\\\\n\\midrule\n"
          + "\n".join(lines) + "\n\\bottomrule\n\\end{tabular}")

    # true positives
    lines = []
    for g, name in TP.items():
        if g not in S:
            continue
        a, b = S[g]["clamp_scale-1"], S[g]["base"]
        gk = g.replace("_", "")
        put(f"{gk}.base.s", num(b["s_mean"][0], 2))
        put(f"{gk}.base.raw", num(b["raw"], 2))
        put(f"{gk}.base.mass", num(b["mass"], 2))
        put(f"{gk}.scale1.sdropci", ci(a["s_drop"]))
        put(f"{gk}.scale1.sdrop", num(a["s_drop"][0], 2))
        put(f"{gk}.scale1.normvs.v", verdict(a["norm_vs_s"]["verdict"]))
        put(f"{gk}.scale1.rawvs.v", verdict(a["raw_vs_s"]["verdict"]))
        put(f"{gk}.black.sdropci", ci(S[g]["black"]["s_drop"]))
        put(f"{gk}.black.sdrop", num(S[g]["black"]["s_drop"][0], 2))
        lines.append(f"{name.capitalize()} & {b['raw']:.2f} & {b['mass']:.2f} & "
                     f"{b['s_mean'][0]:.2f} & {cell(a['s_drop'], False)} & "
                     f"{cell(a['raw_vs_s']['diff'])} & {cell(a['norm_vs_s']['diff'])} & "
                     f"{cell(S[g]['black']['s_drop'], False)} \\\\")
    if not lines:
        table("tp", "\\todo{true-positive groups not run yet}")
    else:
        table("tp", "\\begin{tabular}{lccccccc}\n\\toprule\n"
              "& \\multicolumn{3}{c}{no intervention} & \\multicolumn{3}{c}{suppression, "
              "\\texttt{scale} $-1$} & evidence black \\\\\n"
              "\\cmidrule(lr){2-4}\\cmidrule(lr){5-7}\\cmidrule(lr){8-8}\n"
              "Finding & $\\Praw$ & $m$ & $s$ & drop in $s$ & difference, $\\Praw$ & "
              "difference, $\\Pnorm$ & drop in $s$ \\\\\n\\midrule\n"
              + "\n".join(lines) + "\n\\bottomrule\n\\end{tabular}")

    # the quoted example (first check's film, same feature set)
    ex = next((r for r in rows if r["image"] == "00000655_001.png"), None)
    if ex:
        put("ex.norm", num(ex["arms"]["clamp_scale-1"]["norm"], 3))
        put("ex.clamp", "\\texttt{" + tex_escape(ex["arms"]["clamp_scale-1"]["greedy"].strip())
            + "}")
        put("ex.base", "\\texttt{" + tex_escape(ex["arms"]["base"]["greedy"].strip()) + "}")

    # reproduction: E4's first 20 films against E2 (same films, feature sets and software)
    e2 = {r["image"]: r for r in json.loads((R / "readout_generation_check.json").read_text())
          ["rows"]}
    diffs = [abs(r["arms"][arm][q] - e2[r["image"]][arm][q])
             for r in rows if r["group"] == "fp_banked"
             for arm in ARMS for q in ("raw", "norm")]
    if diffs:
        put("repro.e4e2.maxdiff", num(max(diffs), 3))


# --------------------------------------------------------------------------------------------
# E2: the first generation check
# --------------------------------------------------------------------------------------------
def e2() -> None:
    d = json.loads((R / "readout_generation_check.json").read_text())
    S = d["summary"]
    put("e2.n", d["n"])
    put("e2.nsamples", d["n_samples"])
    put("e2.torch", d["versions"]["torch"].split("+")[0])
    put("e2.transformers", d["versions"]["transformers"])
    for arm, (k, _) in ARMS.items():
        a = S[arm]
        put(f"e2.{k}.banked", num(a["banked_raw_maxdiff"], 3))
        put(f"e2.{k}.greedyno", a["greedy"]["NO"])
        put(f"e2.{k}.s", num(a["sampled_yes_rate"], 2))
        if arm in CLAMP_OPS:
            put(f"e2.{k}.v", verdict(a["verdict"]))
    put("e2.greedy.total", d["n"] * len(ARMS))


# --------------------------------------------------------------------------------------------
# Hand reading of the parse rule, and E4's verdicts with every NONE recoded (not pre-registered)
# --------------------------------------------------------------------------------------------
def hand() -> None:
    h = json.loads((R / "hand_reading_scored.json").read_text())
    put("hand.e4.n", h["e4"]["read"])
    put("hand.e4.agree", h["e4"]["agree"])
    put("hand.e2.n", h["e2"]["outputs_read"])
    put("hand.e2.agree", h["e2"]["outputs_agree"])
    put("hand.e2.distinct", h["e2"]["read"])
    put("hand.e2.distinctagree", h["e2"]["agree"])
    rows = json.loads((R / "readout_sampled_answers.json").read_text())["rows"]
    for to in ("YES", "NO"):
        def rec(p: str, to: str = to) -> str:
            return to if p == "NONE" else p
        recoded = [{**r, "arms": {a: {**v, "greedy_parsed": rec(v["greedy_parsed"]),
                                      "samples_parsed": [rec(p) for p in v["samples_parsed"]]}
                                  for a, v in r["arms"].items()}} for r in rows]
        v = analyze(recoded)["verdicts"]
        for k in ("V1_norm_s", "V1_raw_s", "V2", "V3_s"):
            put(f"sens.{to.lower()}.{k.replace('_', '')}", verdict(v[k]))


# --------------------------------------------------------------------------------------------
# Occlusion: where the evidence sits; effusion check
# --------------------------------------------------------------------------------------------
def occlusion() -> None:
    rows = json.loads((R / "occlusion_readout_audit.json").read_text())["rows"]
    rc = [divmod(r["top_block"], NB) for r in rows]
    put("loc.n", len(rows))
    put("loc.central", sum(2 <= i <= 5 and 2 <= j <= 5 for i, j in rc))
    put("loc.leftheart", sum(j in (4, 5) for _, j in rc))
    eff = [r for r in rows if r["effusion_base"]["norm"] >= 0.5]
    put("occ.eff.n", len(eff))
    put("occ.eff.minnorm", num(min(r["effusion_occ"]["norm"] for r in eff), 3))


# --------------------------------------------------------------------------------------------
# E3: patient-disjoint donor sets
# --------------------------------------------------------------------------------------------
def e3() -> None:
    d = json.loads((R / "donor_sets_patient_disjoint.json").read_text())
    put("e3.ndonor", d["n_donor"])
    put("e3.nfilms", d["n_films"])
    for rule in ("activation", "contrast"):
        for n, v in d["jaccard"][rule].items():
            put(f"e3.jac.{rule}.{n}", num(v, 3))
    ov = list(d["overlap80"].values())
    put("e3.overlap.min", min(ov))
    put("e3.overlap.max", max(ov))
    put("e3.verdict", verdict(d["jaccard_verdict"]))
    A = d["amplification"]
    put("e3.amp.verdict", verdict(A["norm"]["verdict"]))
    put("e3.amp.vsrandom.norm", num(A["norm"]["rise"]["card_donor_10"]
                                    - A["norm"]["rise"]["random_10"], 3))
    put("e3.amp.vsrandom.raw", num(A["raw"]["rise"]["card_donor_10"]
                                   - A["raw"]["rise"]["random_10"], 3))
    put("e3.amp.cardminuseff", num(A["norm"]["rise"]["card_donor_10"]
                                   - A["norm"]["rise"]["eff_donor_10"], 3))
    put("e3.amp.p.eff", num(A["norm"]["p"]["eff_donor"], 3))
    put("e3.amp.p.ptx", num(A["norm"]["p"]["ptx_donor"], 2))
    lines = []
    for key, label in (("card_donor", "Cardiomegaly donors"), ("eff_donor", "Effusion donors"),
                       ("ptx_donor", "Pneumothorax donors"), ("self", "The film's own top $80$"),
                       ("random", "Random $80$")):
        lines.append(f"{label} & {A['norm']['rise'][key + '_10']:.3f} & "
                     f"{A['raw']['rise'][key + '_10']:.3f} \\\\")
    table("amplify", "\\begin{tabular}{lcc}\n\\toprule\n"
          "Feature set & rise in $\\Pnorm$ & rise in $\\Praw$ \\\\\n\\midrule\n"
          + "\n".join(lines) + "\n\\bottomrule\n\\end{tabular}")
    old = json.loads((R / "clamp_amplify_donor_specificity.json").read_text())  # raw readout only
    for key, k in (("card_donor", "card"), ("eff_donor", "eff"), ("ptx_donor", "ptx")):
        put(f"e3.old.{k}", num(old["rise"][f"{key}_10"], 3))
    J = d["jaccard"]
    table("jaccard", "\\begin{tabular}{lccc}\n\\toprule\n"
          "Selection rule & $N{=}20$ & $N{=}80$ & $N{=}320$ \\\\\n\\midrule\n"
          "Top activation & " + " & ".join(f"{J['activation'][n]:.3f}" for n in
                                            ("20", "80", "320")) + " \\\\\n"
          "Contrast, positive minus negative donors & "
          + " & ".join(f"{J['contrast'][n]:.3f}" for n in ("20", "80", "320"))
          + " \\\\\n\\bottomrule\n\\end{tabular}")


# --------------------------------------------------------------------------------------------
# E5: contrastive and anchored feature sets
# --------------------------------------------------------------------------------------------
E5_GROUPS = {"fp": "fp", "tp_cardiomegaly": "tpcard", "tp_effusion": "tpeff"}
E5_ARMS = {"top": ("top", "Own top $80$ (the paper's)"),
           "con_card": ("concard", "Cardiomegaly contrast"),
           "con_eff": ("coneff", "Effusion contrast"),
           "rand_act": ("rand", "Random active $80$"),
           "anch_evid": ("evid", "Anchored, evidence block"),
           "anch_border": ("border", "Anchored, border block")}


def e5() -> None:
    d = json.loads((R / "clamp_contrastive_answers.json").read_text())
    if "verdicts" in d:
        res = {"summary": d["summary"], "verdicts": d["verdicts"]}
    else:
        n_test = 80  # E4's fp (40) + tp_cardiomegaly (20) + tp_effusion (20)
        warnings.append(f"E5 has no saved verdicts ({len(d['rows'])} of {n_test} films)")
        res = e5mod.analyze(d["rows"], n_boot=2000)
    put("e5.ndonor", min(len(v) for v in d["donors"].values()))
    put("e5.jaccon", num(d["jaccard_con"], 3))
    put("e5.nsamples", d.get("n_samples", 30))
    S = res["summary"]
    for g, gk in E5_GROUPS.items():
        if g not in S:
            continue
        put(f"e5.{gk}.n", S[g]["top"]["n"])
        put(f"e5.{gk}.base.s", num(np.mean([e5mod.yes_rate(r["arms"]["base"]["samples_parsed"])
                                            for r in d["rows"] if r["group"] == g])))
        put(f"e5.{gk}.base.raw", num(np.mean([r["arms"]["base"]["raw"]
                                              for r in d["rows"] if r["group"] == g])))
        for arm, (ak, _) in E5_ARMS.items():
            a = S[g][arm]
            put(f"e5.{gk}.{ak}.sdrop", ci(a["s_drop"]))
            put(f"e5.{gk}.{ak}.nactive", num(a["n_active"], 1))
            put(f"e5.{gk}.{ak}.overlap", num(a["overlap_top"], 1))
            put(f"e5.{gk}.{ak}.normv", verdict(a["norm_verdict"][0] if isinstance(
                a["norm_verdict"], list) else a["norm_verdict"]))
            put(f"e5.{gk}.{ak}.rawv", verdict(a["raw_verdict"][0] if isinstance(
                a["raw_verdict"], list) else a["raw_verdict"]))
            put(f"e5.{gk}.{ak}.raw", num(a["raw"]))
    V = res["verdicts"]
    for k, key in (("S1", "S1"), ("S2", "S2"), ("S3", "S3"),
                   ("S3_tp_cardiomegaly", "S3.tpcard"), ("S3_tp_effusion", "S3.tpeff")):
        if k in V:
            put(f"e5.{key}", verdict(V[k]))
        if f"{k}_ci" in V:
            put(f"e5.{key}.ci", ci(V[f"{k}_ci"], sign=True))
    if "S1_detail" in V:
        for k, key in (("a", "a"), ("b", "b"), ("con_card_minus_rand", "cardrand"),
                       ("con_eff_minus_rand", "effrand")):
            put(f"e5.S1.{key}", ci(V["S1_detail"][k], sign=True))
    cols = [g for g in E5_GROUPS if g in S]
    head = {"fp": "False positives", "tp_cardiomegaly": "Cardiomegaly, correct",
            "tp_effusion": "Effusion, correct"}
    lines = []
    for arm, (_, label) in E5_ARMS.items():
        cells = []
        for g in cols:
            m, lo, hi = S[g][arm]["s_drop"]
            cells.append(f"${m:+.2f}$ {{\\scriptsize$[{lo:+.2f},\\,{hi:+.2f}]$}}")
        a = S["fp"][arm] if "fp" in S else S[cols[0]][arm]
        lines.append(f"{label} & ${a['n_active']:.0f}$ & ${a['overlap_top']:.0f}$ & "
                     + " & ".join(cells) + " \\\\")
    head = {"fp": "false positives", "tp_cardiomegaly": "cardiomegaly", "tp_effusion": "effusion"}
    ntp = sum(g != "fp" for g in cols)
    top = ("& & & " + ("& " if "fp" in cols else "")
           + (f"\\multicolumn{{{ntp}}}{{c}}{{correct calls}}" if ntp else "") + " \\\\\n")
    table("e5", "\\begin{tabular}{lcc" + "c" * len(cols) + "}\n\\toprule\n"
          "& & & \\multicolumn{" + str(len(cols)) + "}{c}{drop in $s$} \\\\\n"
          "\\cmidrule(lr){4-" + str(3 + len(cols)) + "}\n" + top
          + "Feature set & active & in top $80$ & " + " & ".join(head[g] for g in cols)
          + " \\\\\n\\midrule\n" + "\n".join(lines) + "\n\\bottomrule\n\\end{tabular}")


# --------------------------------------------------------------------------------------------
# E6: the stratified evaluation, scored four ways, in each model
# --------------------------------------------------------------------------------------------
E6_MODELS = {"medgemma": ("mg", "MedGemma 1.5 4B"), "lingshu": ("ls", "Lingshu-7B"),
             "chexagent": ("cx", "CheXagent-2 3B")}
E6_FINDINGS = {"cardiomegaly": "card", "effusion": "eff", "pneumothorax": "ptx"}


def e6() -> None:
    runs = {}
    for m in E6_MODELS:
        f = R / f"readout_eval_answers_{m}.json"
        if f.exists():
            runs[m] = json.loads(f.read_text())
    if "medgemma" not in runs:
        raise FileNotFoundError(2, "missing", str(R / "readout_eval_answers_medgemma.json"))
    rf = R / "readout_eval_resolution.json"
    resol = json.loads(rf.read_text()) if rf.exists() else None
    if resol is None:
        warnings.append("E6: missing readout_eval_resolution.json (matched-resolution column)")
    lines = []
    for m, d in runs.items():
        mk, label = E6_MODELS[m]
        rm = resol["models"].get(m) if resol else None
        put(f"e6.{mk}.nonesamples",
            sum(p == "NONE" for r in d["rows"] for p in r["samples_parsed"]))
        put(f"e6.{mk}.nsamplestotal", f"{d['n_samples'] * len(d['rows']):,}".replace(",", "{,}"))
        masses = [d["by_finding"][f]["mass_mean"] for f in E6_FINDINGS if f in d["by_finding"]]
        put(f"e6.{mk}.massmin", num(min(masses)))
        put(f"e6.{mk}.massmax", num(max(masses)))
        if rm:
            tied = [rm[f]["tied"] for f in E6_FINDINGS]
            put(f"e6.{mk}.tiedmin", f"{100 * min(tied):.0f}\\%")
            put(f"e6.{mk}.tiedmax", f"{100 * max(tied):.0f}\\%")
            for f, fk in E6_FINDINGS.items():
                put(f"e6.{mk}.{fk}.s0n", rm[f]["s0_n"])
                put(f"e6.{mk}.{fk}.s0pos", rm[f]["s0_pos"])
                if rm[f]["s0_auc_raw"] is not None:
                    put(f"e6.{mk}.{fk}.s0auc", num(rm[f]["s0_auc_raw"]))
                for k in ("raw", "norm"):  # stored as AUC(s) - AUC(q); shown as q minus s
                    pt, lo, hi = rm[f][f"s-q{k}"]
                    put(f"e6.{mk}.{fk}.matched.{k}", ci((-pt, -hi, -lo), 3, sign=True))
        if "verdict" in d:
            res = {"by_finding": d["by_finding"], "verdict": d["verdict"]}
        else:
            warnings.append(f"E6 {m} is partial ({len(d['rows'])} film-finding pairs, no verdict)")
            res = e6mod.analyze(d["rows"])
        put(f"e6.{mk}.verdict", verdict(res["verdict"]))
        put(f"e6.{mk}.nsamples", d.get("n_samples", 20))
        put(f"e6.{mk}.nlevels", d.get("n_samples", 20) + 1)
        if m == "medgemma":
            put("e6.npairs", len(d["rows"]))
        lines.append(f"\\multicolumn{{7}}{{l}}{{\\emph{{{label}}}}} \\\\")
        for f, fk in E6_FINDINGS.items():
            if f not in res["by_finding"]:
                continue
            r = res["by_finding"][f]
            put(f"e6.{mk}.{fk}.npos", r["n_pos"])
            put(f"e6.{mk}.{fk}.nneg", r["n_neg"])
            put(f"e6.{mk}.{fk}.mass", num(r["mass_mean"]))
            put(f"e6.{mk}.{fk}.greedynone", r["greedy_none"])
            for k in e6mod.SCORES:
                lo, hi = r["ci"][k]
                put(f"e6.{mk}.{fk}.auc.{k}", ci((r["auc"][k], lo, hi), 3))
                put(f"e6.{mk}.{fk}.acc.{k}", num(r["accuracy"][k]))
            for k in ("raw", "norm"):
                put(f"e6.{mk}.{fk}.{k}vs", ci(r["diff"][f"{k}-s"], 3, sign=True))
                put(f"e6.{mk}.{fk}.dis.{k}", r["calls_disagree_with_sampled"][k])
            cells = [f"{r['auc'][k]:.3f}" for k in e6mod.SCORES]
            fmt = "${:+.3f}$ {{\\scriptsize$[{:+.3f},\\,{:+.3f}]$}}"
            cells += [fmt.format(*r["diff"][f"{k}-s"]) for k in ("raw", "norm")]
            lines.append(f"{f.capitalize()} ({r['n_pos']}/{r['n_neg']}) & "
                         + " & ".join(cells) + " \\\\")
        lines.append("\\midrule")
    table("e6", "\\begin{tabular}{lcccccc}\n\\toprule\n"
          "& \\multicolumn{4}{c}{AUC} & \\multicolumn{2}{c}{AUC minus AUC of $s$} \\\\\n"
          "\\cmidrule(lr){2-5}\\cmidrule(lr){6-7}\n"
          "Finding (pos/neg) & $\\Praw$ & $\\Pnorm$ & $s$ & greedy & $\\Praw$ & $\\Pnorm$ "
          "\\\\\n\\midrule\n" + "\n".join(lines[:-1])
          + "\n\\bottomrule\n\\end{tabular}")
    if resol:
        allm = [rm[f][f"s-q{k}"] for rm in resol["models"].values() for f in E6_FINDINGS
                for k in ("raw", "norm")]
        put("e6.res.maxabs", num(max(abs(x[0]) for x in allm), 2))
        if not all(lo <= 0 <= hi for _, lo, hi in allm):
            warnings.append("E6 matched resolution: some interval excludes 0; prose says none does")
        for f, fk in E6_FINDINGS.items():
            v = resol["across"]["by_finding"][f]["qraw"]
            put(f"e6.res.rank.{fk}", ci(v, 3, sign=True))
        if not all(resol["across"]["by_finding"][f]["qraw"][2] < 0 for f in E6_FINDINGS):
            warnings.append("E6 matched resolution: a model comparison does not separate")
    others = [m for m in runs if m != "medgemma"]
    if others:
        c = e6mod.compare(runs["medgemma"], runs[others[0]])
        put("e6.rank.model", E6_MODELS[others[0]][1])
        put("e6.rank.verdict", verdict(c["verdict"]))
        for f, fk in E6_FINDINGS.items():
            if f in c["by_finding"]:
                for k in e6mod.SCORES:
                    put(f"e6.rank.{fk}.{k}", ci(c["by_finding"][f]["auc_diff"][k], 3, sign=True))


# --------------------------------------------------------------------------------------------
# E7: the corrected evaluation test (matched resolution, fresh patients)
# --------------------------------------------------------------------------------------------
def e7() -> None:  # noqa: PLR0915
    f = R / "readout_eval_matched.json"
    if not f.exists():
        raise FileNotFoundError(2, "missing", str(f))
    res = json.loads(f.read_text())
    runs = {m: json.loads((R / f"readout_eval_matched_{m}.json").read_text())
            for m in res["models"]}
    rows = next(iter(runs.values()))["rows"]
    put("e7.npairs", len(rows))
    put("e7.npat", len({e6mod.patient(r["image"]) for r in rows}))
    put("e7.nfilms", len({r["image"] for r in rows}))
    put("e7.nsamples", res["n_samples"])
    put("e7.nboot", f"{res['n_boot']:,}".replace(",", "{,}"))
    lines, allD = [], []
    for m, r in res["models"].items():
        mk, label = E6_MODELS[m]
        d = runs[m]
        put(f"e7.{mk}.verdict", verdict(r["e7"]["verdict"]))
        put(f"e7.{mk}.e6rule", verdict(r["reported"]["e6_rule_verdict"]))
        put(f"e7.{mk}.nonesamples",
            sum(p == "NONE" for x in d["rows"] for p in x["samples_parsed"]))
        put(f"e7.{mk}.nsamplestotal", f"{d['n_samples'] * len(d['rows']):,}".replace(",", "{,}"))
        put(f"e7.{mk}.gatemax", num(max(x["first_token_diff"] for x in d["rows"]), 3))
        rep = r["reported"]["by_finding"]
        tied = [rep[g]["tied"] for g in E6_FINDINGS]
        put(f"e7.{mk}.tiedmin", f"{100 * min(tied):.0f}\\%")
        put(f"e7.{mk}.tiedmax", f"{100 * max(tied):.0f}\\%")
        masses = [rep[g]["mass_mean"] for g in E6_FINDINGS]
        put(f"e7.{mk}.massmin", num(min(masses)))
        put(f"e7.{mk}.massmax", num(max(masses)))
        ds = [r["e7"]["by_finding"][g][k]["D"] for g in E6_FINDINGS for k in ("raw", "norm")]
        put(f"e7.{mk}.maxhw", num(max((hi - lo) / 2 for _, lo, hi in ds), 3))
        put(f"e7.{mk}.maxbound", num(max(max(-lo, hi) for _, lo, hi in ds), 2))
        if not all(lo <= 0 <= hi for _, lo, hi in ds):
            warnings.append(f"E7 {m}: some interval of D excludes 0; prose says none does")
        gaps = [rep[g]["e6_rule_diff"][f"{k}-s"][0] for g in E6_FINDINGS for k in ("raw", "norm")]
        put(f"e7.{mk}.gapmin", num(min(gaps), 3))
        put(f"e7.{mk}.gapmax", num(max(gaps), 3))
        # After the run, not pre-registered: the share of films whose yes count lies outside the
        # central 95% of Binomial(n, P), the planning simulation's assumption, per finding/readout.
        n = d["n_samples"]
        out = []
        for g in E6_FINDINGS:
            rs = [x for x in d["rows"] if x["finding"] == g]
            k = np.array([sum(p == "YES" for p in x["samples_parsed"]) for x in rs])
            for key in ("raw", "norm"):
                pr = np.array([x[key] for x in rs])
                out.append(np.mean((k < binom.ppf(0.025, n, pr)) | (k > binom.ppf(0.975, n, pr))))
        put(f"e7.{mk}.outbinmin", f"{100 * min(out):.0f}\\%")
        put(f"e7.{mk}.outbinmax", f"{100 * max(out):.0f}\\%")
        lines.append(f"\\multicolumn{{7}}{{l}}{{\\emph{{{label}}}}} \\\\")
        for g, fk in E6_FINDINGS.items():
            v, t = r["e7"]["by_finding"][g], rep[g]
            put(f"e7.{mk}.{fk}.npos", v["n_pos"])
            put(f"e7.{mk}.{fk}.nneg", v["n_neg"])
            put(f"e7.{mk}.{fk}.auc.s", num(v["auc_s"], 3))
            put(f"e7.{mk}.{fk}.s0n", t["s0_n"])
            put(f"e7.{mk}.{fk}.s0pos", t["s0_pos"])
            if t["s0_auc_raw"] is not None:
                put(f"e7.{mk}.{fk}.s0auc", num(t["s0_auc_raw"]))
            for k in ("raw", "norm"):
                put(f"e7.{mk}.{fk}.auc.{k}", num(v[k]["auc_P"], 3))
                put(f"e7.{mk}.{fk}.eauc.{k}", num(v[k]["eauc_q"], 3))
                put(f"e7.{mk}.{fk}.D.{k}", ci(v[k]["D"], 3, sign=True))
                pt, lo, hi = t["e6_rule_diff"][f"{k}-s"]  # stored readout minus s; shown s minus
                put(f"e7.{mk}.{fk}.unmatched.{k}", ci((-pt, -hi, -lo), 3, sign=True))
                allD.append(v[k]["D"])
            fmt = "${:+.3f}$ {{\\scriptsize$[{:+.3f},\\,{:+.3f}]$}}"
            cells = [f"{v['raw']['auc_P']:.3f}", f"{v['norm']['auc_P']:.3f}", f"{v['auc_s']:.3f}",
                     fmt.format(-t["e6_rule_diff"]["raw-s"][0], -t["e6_rule_diff"]["raw-s"][2],
                                -t["e6_rule_diff"]["raw-s"][1]),
                     fmt.format(*v["raw"]["D"]), fmt.format(*v["norm"]["D"])]
            lines.append(f"{g.capitalize()} & " + " & ".join(cells) + " \\\\")
        lines.append("\\midrule")
    ns = {v[k] for r in res["models"].values() for v in r["e7"]["by_finding"].values()
          for k in ("n_pos", "n_neg")}
    if len(ns) != 1:
        warnings.append(f"E7: unequal class sizes {sorted(ns)}; prose says one size")
    put("e7.nper", min(ns))
    put("e7.maxabsD", num(max(abs(x[0]) for x in allD), 3))
    put("e7.maxhw", num(max((x[2] - x[1]) / 2 for x in allD), 3))
    table("e7", "\\begin{tabular}{lcccccc}\n\\toprule\n"
          "& \\multicolumn{3}{c}{AUC} & \\multicolumn{3}{c}{AUC of $s$ minus} \\\\\n"
          "\\cmidrule(lr){2-4}\\cmidrule(lr){5-7}\n"
          "Finding & $\\Praw$ & $\\Pnorm$ & $s$ & AUC of $\\Praw$ "
          "& $\\mathbb{E}\\,$AUC of $q_{\\text{raw}}$ "
          "& $\\mathbb{E}\\,$AUC of $q_{\\text{norm}}$ \\\\\n"
          "\\midrule\n" + "\n".join(lines[:-1]) + "\n\\bottomrule\n\\end{tabular}")
    for g, fk in E6_FINDINGS.items():
        for k, v in res["across"]["by_finding"][g].items():
            put(f"e7.rank.{fk}.{k}", ci(v, 3, sign=True))
    acr = [v for g in E6_FINDINGS for v in res["across"]["by_finding"][g].values()]
    if not (all(hi < 0 for _, _, hi in acr) or all(lo > 0 for _, lo, _ in acr)):
        warnings.append("E7 across: the scores do not all separate the models the same way")


# --------------------------------------------------------------------------------------------
# Appendices from earlier runs: prompt phrasings, attention vs causal effect, the dictionary
# --------------------------------------------------------------------------------------------
PROMPTS = {"plain": "plain", "noformat": "no_format", "persona": "persona", "gloss": "gloss"}
CELLS = {"apfp": "card_neg_AP", "fp": "cardiomegaly_neg", "tpcard": "cardiomegaly_pos",
         "tpptx": "pneumothorax", "tpeff": "effusion"}


def load(path: Path) -> dict:
    return json.loads(path.read_text())


def prompts() -> None:
    d = load(R / "readout_prompt_confound.json")
    s = d["summary"]
    put("ps.n", d["n"])
    for k, src in PROMPTS.items():
        for q in ("raw", "norm", "mass"):
            put(f"ps.{k}.{q}", num(s[src][q], 3))
        if k != "plain":
            for q in ("raw", "norm"):
                put(f"ps.{k}.d{q}", num(s[src][q] - s["plain"][q], 3, sign=True))


def attention() -> None:
    rho, shuf = {}, {}
    for k, f in CELLS.items():
        d = load(R / f"causal_map_{f}.json")
        # the top-level rho is NaN where a film's map is constant; average over the films
        rho[k] = np.nanmean([r["rho"] for r in d["records"]])
        shuf[k] = np.nanmean([r["rho_shuffled"] for r in d["records"]])
        put(f"attn.{k}.n", d["n"])
        put(f"attn.{k}.best", num(d["best_block_mean"], 3))
        put(f"attn.{k}.nrem", d["n_removable"])
        put(f"attn.{k}.rho", num(rho[k], 3, sign=True))
        put(f"attn.{k}.shuf", num(shuf[k], 3, sign=True))
    put("attn.rhomin", num(min(rho.values()), 3, sign=True))
    put("attn.rhomax", num(max(rho.values()), 3, sign=True))
    put("attn.shufmin", num(min(shuf.values()), 3, sign=True))
    put("attn.shufmax", num(max(shuf.values()), 3, sign=True))
    put("attn.eff.bestmax", num(load(R / "causal_map_effusion.json")["best_block_max"], 3))
    put("attn.ptx.bestmax", num(load(R / "causal_map_pneumothorax.json")["best_block_max"], 3))
    pp = load(R / "attn_causal_map.json")["A"]
    put("attn.perpatch", num(pp["mean_rho"], 3, sign=True))
    # film-bootstrap interval on the per-patch mean, computed here because the run did not save one
    r = np.array([x["rho"] for x in pp["records"]])
    b = np.random.default_rng(0).choice(r, (10_000, len(r))).mean(1)
    put("attn.perpatch.ci", ci((r.mean(), *np.percentile(b, [2.5, 97.5])), 3, sign=True))
    put("attn.perpatch.shuf", num(pp["mean_rho_shuffled"], 3, sign=True))
    put("attn.perpatch.n", pp["n_films"])
    pr = load(R / "feats_causal_vs_inert_norm.json")
    put("probe.auc", num(pr["auc_features"], 3))
    put("probe.null", num(pr["auc_shuffled_mean"], 3))
    put("probe.nullsd", num(pr["null_sd"], 3))
    put("probe.pix", num(pr["auc_pixels"], 3))


def clt_layers() -> int:
    """Layers of the CLT, from its recorded allocation: W_enc plus span+1 decoder blocks per layer."""
    c = load(R / "clt_scale_result.json")
    return c["params"] // (c["n_features"] * c["d_model"] * (c["span"] + 2))


def dictionary() -> None:
    c = load(R / "clt_scale_result.json")
    put("clt.params", f"{c['params'] / 1e9:.2f}")
    # 'params' counts every allocated decoder block; a source layer l has no block for offsets past
    # the last layer, so those rows are never used or trained
    n_lay, block = clt_layers(), c["n_features"] * c["d_model"]
    used = (n_lay + sum(n_lay - o for o in range(c["span"] + 1))) * block
    put("clt.used", f"{used / 1e9:.2f}")
    put("clt.unused", f"{(c['params'] - used) / 1e9:.2f}")
    put("clt.span0.params", f"{load(R / 'clt_span0_result.json')['params'] / 1e9:.2f}")
    a1 = load(ROOT / "results/a1_fidelity.json")
    put("a1.img", num(a1["mean_image_fvu"], 2))
    put("a1.txt", num(a1["mean_text_fvu"], 2))
    # "image" in these files means prompts with a radiograph, scored at the last position
    live = load(R / "replacement_live.json")["image"]
    span0 = load(R / "clt_replacement_span0.json")["image"]
    cached = load(R / "clt_replacement.json")["image"]
    put("rep.n", live["n"])
    put("rep.live.agree", f"{100 * live['top1_agreement']:.0f}")
    put("rep.live.kl", num(live["kl_mean"], 3))
    put("rep.span0.agree", f"{100 * span0['top1_agreement']:.0f}")
    put("rep.span0.kl", num(span0["kl_mean"], 3))
    put("rep.span0.agreefrac", num(span0["top1_agreement"], 2))
    put("rep.cached.agreefrac", num(cached["top1_agreement"], 2))
    pb = load(R / "clt_prompt_battery.json")["results"]["constr_cardio"]
    put("rep.yn.agree", sum(r["agree"] for r in pb))
    put("rep.yn.n", len(pb))
    put("rep.yn.kl", num(np.mean([r["kl"] for r in pb]), 1))
    fe = {m["name"]: m for m in load(R / "fair_eval.json")["models"]}
    put("fvu.perlayer.img", num(fe["per_layer"]["fvu_image"], 3))
    put("fvu.onthefly.img", num(fe["onthefly"]["fvu_image"], 3))
    fb = load(R / "clt_fvu_by_prompt.json")["means"]
    probes = ("probe_cardio", "probe_effusion", "probe_trivial")
    put("fvu.txt.train", num(fb["train_prompt"]["text"], 3))
    put("fvu.txt.probes", num(np.mean([fb[k]["text"] for k in probes]), 3))
    put("fvu.txt.nprobes", len(probes))
    if len({round(v["image"], 6) for v in fb.values()}) != 1:
        warnings.append("image FVU differs across prompts; App C says identical")
    put("fvu.img.nprompts", len(fb))
    put("fvu.img", num(fb["train_prompt"]["image"], 3))


def extras() -> None:
    ex = load(R / "occlusion_readout_audit.json")["rows"][0]
    put("loc.ex.base", num(ex["base"]["norm"], 2))
    put("loc.ex.black", num(ex["black"]["norm"], 2))
    h = load(R / "hand_reading_scored.json")
    dis = h["e4"]["disagreements"] + h["e2"]["disagreements"]
    put("hand.dis.n", len(dis))
    put("hand.dis.rulenone", sum(d["rule"] == "NONE" for d in dis))
    put("hand.dis.rulenoreadernone", sum(d["rule"] == "NO" and d["reader"] == "NONE" for d in dis))
    put("hand.dis.ruleyesreadernone",
        sum(d["rule"] == "YES" and d["reader"] == "NONE" for d in dis))
    a = load(R / "readout_eval_answers_chexagent_aborted_nl.json")["rows"]
    put("e6.cxnl.n", len(a))
    put("e6.cxnl.yes", sum(r["template_nl_top"] == "Yes" for r in a))
    put("e6.cxnl.no", sum(r["template_nl_top"] == "No" for r in a))


# --------------------------------------------------------------------------------------------
# Post-hoc checks of E4's answers: other parse rules, text degeneration, ceiling
# --------------------------------------------------------------------------------------------
def checks() -> None:
    c = json.loads((R / "answer_text_checks.json").read_text())
    arms = list(CLAMP_OPS)
    norm = [c["parse"][rule][f"{a}.norm"] for rule in ("last", "mention", "strict") for a in arms]
    if any(v["verdict"] != "MISREADS" or v["diff"][0] >= 0 for v in norm):
        warnings.append("post-hoc parse rules: some P_norm verdict is not MISREADS; prose says all")
    put("alt.norm.min", num(min(-v["diff"][0] for v in norm), 2))
    put("alt.norm.max", num(max(-v["diff"][0] for v in norm), 2))
    put("alt.last.changed", f"{c['parse']['last']['changed']:,}".replace(",", "{,}"))
    put("alt.nsamples", f"{4 * 50 * c['n_films']:,}".replace(",", "{,}"))
    tx = c["text"]
    pct = lambda x: f"{100 * x:.1f}\\%"  # noqa: E731
    put("text.base.trunc", pct(tx["base"]["truncated"]))
    put("text.scale1.trunc", pct(tx["clamp_scale-1"]["truncated"]))
    put("text.scale2.trunc", pct(tx["clamp_scale-2"]["truncated"]))
    put("text.clamp.noimgmax", pct(max(tx[a]["no_image"] for a in arms)))
    put("text.clamp.formatmax", pct(max(tx[a]["mentions_format"] for a in arms)))
    ce = [c["ceiling"][a] for a in arms]
    put("ceil.rhomin", num(min(x["spearman"] for x in ce), 2))
    put("ceil.rhomax", num(max(x["spearman"] for x in ce), 2))
    put("ceil.tinymin", min(x["n_tiny"] for x in ce))
    put("ceil.tinymax", max(x["n_tiny"] for x in ce))
    put("ceil.sdroptinymin", num(min(x["sdrop_tiny"] for x in ce), 2))
    put("ceil.sdroptinymax", num(max(x["sdrop_tiny"] for x in ce), 2))
    put("ceil.lowmin", num(min(-x["diff_low_margin"][0] for x in ce), 2))
    put("ceil.lowmax", num(max(-x["diff_low_margin"][0] for x in ce), 2))
    put("ceil.highmin", num(min(-x["diff_high_margin"][0] for x in ce), 2))
    put("ceil.highmax", num(max(-x["diff_high_margin"][0] for x in ce), 2))
    if not all(x["diff_low_margin"][0] < x["diff_high_margin"][0] for x in ce):
        warnings.append("ceiling: shortfall not larger on the low-margin half in every arm")


# --------------------------------------------------------------------------------------------
# E8: the same edits added to the live MLPs (clamp_live_mlp.json; text shares from the checks)
# --------------------------------------------------------------------------------------------
def e8() -> None:
    d = json.loads((R / "clamp_live_mlp.json").read_text())
    tx = json.loads((R / "answer_text_checks.json").read_text())["e8_text"]
    arms = list(CLAMP_OPS)
    S = d["summary"]
    pct = lambda x: f"{100 * x:.0f}\\%"  # noqa: E731
    put("e8.nfilms", len(d["rows"]))
    put("e8.verdict", verdict(d["verdict"]))
    put("e8.basediff", num(d["base_max_diff_from_e4"], 3))
    for a in arms:
        k = ARMS[a][0]
        put(f"e8.{k}.verdict", verdict(S[a]["norm_vs_s"]["verdict"]))
        put(f"e8.{k}.normvs", ci(S[a]["norm_vs_s"]["diff"], sign=True))
        put(f"e8.{k}.normvsc", ci(S[a]["norm_vs_c"]["diff"], sign=True))
    for key, xs, fmt in (("s", [S[a]["s_mean"][0] for a in arms], num),
                         ("norm", [S[a]["norm"] for a in arms], num),
                         ("mass", [S[a]["mass"] for a in arms], num),
                         ("none", [tx[a]["none"] for a in arms], pct),
                         ("nonefrozen", [tx[a]["none_frozen"] for a in arms], pct),
                         ("opensI", [S[a]["opening"]["i"]["share"] for a in arms], pct)):
        put(f"e8.{key}.min", fmt(min(xs)))
        put(f"e8.{key}.max", fmt(max(xs)))
    put("e8.base.s", num(S["base"]["s_mean"][0]))
    put("e8.trunc.max", pct(max(tx[a]["truncated"] for a in arms)))
    put("e8.noimg.max", pct(max(tx[a]["no_image"] for a in arms)))
    c = [S[a]["norm_vs_c"] for a in arms]
    if any(v["verdict"] != "MISREADS" or v["diff"][0] <= 0 for v in c):
        warnings.append("E8: P_norm against c is not MISREADS-positive in every arm; prose says so")
    if d["base_max_diff_from_e4"] > 1e-3:
        warnings.append("E8: base arm differs from E4's base; prose says it reproduces it")


def e9() -> None:
    d = json.loads((R / "clamp_live_dose.json").read_text())
    pct = lambda x: f"{100 * x:.0f}\\%"  # noqa: E731
    put("e9.verdict", verdict(d["verdict"]))
    put("e9.tau", pct(d["tau"]))
    put("e9.target", num(d["e4_target_s_drop"]))
    put("e9.neligible", len(d["eligible"]))
    put("e9.ndoses", len(d["doses"]))
    put("e9.basediff", num(d["base_max_diff_from_e8"], 3))
    if d["matched"] is None:
        return
    m, S = d["doses"][d["matched"]], d["summary"][d["matched"]]
    put("e9.c", num(m["c"]))
    put("e9.sdrop", ci(m["s_drop"]))
    put("e9.normdrop", ci(S["norm_drop"]))
    put("e9.rawdrop", ci(S["raw_drop"]))
    put("e9.nonanswer", pct(m["nonanswer"]))
    put("e9.mass", num(S["mass"]))
    put("e9.norm", num(S["norm"]))
    put("e9.s", num(S["s_mean"][0]))
    put("e9.normvs", ci(m["norm_vs_s"]["diff"], 3, sign=True))
    put("e9.pno", num(S["mass"] - S["raw"]))
    put("e9.normvsc", ci(m["norm_vs_c"]["diff"], sign=True))
    put("e9.normvsc.verdict", verdict(m["norm_vs_c"]["verdict"]))
    put("e9.rawvs", ci(m["raw_vs_s"]["diff"], sign=True))
    put("e9.rawvs.verdict", verdict(m["raw_vs_s"]["verdict"]))
    put("e9.ratio", f"{m['s_drop'][0] / d['e4_target_s_drop']:.1f}")
    o = S["opening"]
    put("e9.based", num(o["based"]["share"]))
    put("e9.pyesbased", num(o["based"]["p_yes"]))
    put("e9.opensno", num(o["no"]["share"]))
    put("e9.base.based", num(d["summary"]["base"]["opening"]["based"]["share"]))
    # the next weaker strength, and every stronger one
    weaker = [x for x in d["doses"].values() if x["c"] > m["c"]]
    stronger = [x for x in d["doses"].values() if x["c"] < m["c"]]
    if weaker:
        w = min(weaker, key=lambda x: x["c"])
        put("e9.weak.c", f"{w['c']:g}")
        put("e9.weak.sdrop", ci(w["s_drop"]))
    if stronger:
        put("e9.strong.namin", pct(min(x["nonanswer"] for x in stronger)))
        put("e9.strong.namax", pct(max(x["nonanswer"] for x in stronger)))
        put("e9.strong.verdicts", ", ".join(sorted({verdict(x["norm_vs_s"]["verdict"])
                                                    for x in stronger})))
        put("e9.strong.cverdicts", ", ".join(sorted({verdict(x["norm_vs_c"]["verdict"])
                                                     for x in stronger})))
    el = [d["doses"][a] for a in d["eligible"]]
    put("e9.eligible.cs", ", ".join(f"${x['c']:g}$" for x in el))
    put("e9.eligible.normvsmin", num(min(x["norm_vs_s"]["diff"][0] for x in el), sign=True))
    put("e9.eligible.normvsmax", num(max(x["norm_vs_s"]["diff"][0] for x in el), sign=True))
    put("e9.eligible.verdicts", ", ".join(sorted({verdict(x["norm_vs_s"]["verdict"])
                                                  for x in el})))


# --------------------------------------------------------------------------------------------
# Compute: wall-clock time of each generation run, from the last progress line of its log
# --------------------------------------------------------------------------------------------
LOGS = {"e2": "readout_generation_check", "e4": "readout_sampled_answers",
        "e5": "clamp_contrastive_answers", "e6mg": "readout_eval_answers_medgemma",
        "e6cx": "readout_eval_answers_chexagent", "e7mg": "readout_eval_matched_medgemma",
        "e7cx": "readout_eval_matched_chexagent"}


def compute() -> None:
    for key, name in LOGS.items():
        f = R / "logs" / f"{name}.log"
        if not f.exists():
            raise FileNotFoundError(2, "missing", str(f))
        done = [m for m in re.finditer(r"\[(\d+)/(\d+) (\d+)s\]", f.read_text())
                if m.group(1) == m.group(2)]
        if not done:
            raise ValueError(f"{f.name}: no completed progress line")
        put(f"compute.{key}", round(int(done[-1].group(3)) / 60))


TABLES = {"e3": ("amplify", "jaccard"), "e4": ("main", "v1", "routes", "tp"), "e5": ("e5",),
          "e6": ("e6",), "e7": ("e7",)}


def main() -> None:
    for step in (e2, hand, occlusion, e3, e4, e5, e6, e7, checks, e8, e9, prompts, attention,
                 dictionary, extras, compute):
        try:
            step()
        except FileNotFoundError as e:
            warnings.append(f"{step.__name__}: missing {Path(e.filename).name}")
            for name in TABLES.get(step.__name__, ()):  # never leave a stale table in place
                table(name, f"\\todo{{table {name}: {tex_escape(Path(e.filename).name)} missing}}")
    head = ["% generated by paper/make_numbers.py; do not edit"]
    head += [f"\\PackageWarning{{numbers}}{{{w}}}" for w in warnings]
    body = [f"\\defval{{{k}}}{{{v}}}" for k, v in sorted(vals.items())]
    (OUT / "numbers.tex").write_text("\n".join(head + body) + "\n")
    print(f"wrote paper/numbers.tex ({len(vals)} values) and paper/tables/")
    for w in warnings:
        print("WARNING", w)


if __name__ == "__main__":
    main()
